### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TheFerryn** [TheFerryn/Flame#7]
Маленький список планов, основанный на предложениях со стороны пользователей. Если вы не нашли вашу идею здесь — будьте добры, уточните об этом на сервере поддержки.

**Основной функционал**
- [x] Улучшенная система предупреждений.
- [ ] Система уровней.
- [ ] Панель управления ботом & API.

**Модерация & Авто-модерация**
- [] Защита от приглашений.
- [] Сторонние фильтры (CAPS, флуд, матерные слова и т.д).
- [x] Команда `unban`.
- [ ] Улучшенная система мьютов.

**Экономика**
- [] Более продуманная система ограблений.
- [] Ежедневное колесо удачи, с 50% шансом получить бонус.
- [] Новые работы (пчеловодство, лесорубка).
- [] Больше разновидностей инструментов.
- [] Пассивный доход.

**Comment by ElemelkyaDima** [comment]
Команда кетчупа и гуся
